language: go
go:
  - 1.5
  - 1.6
before_script:
  - curl -L https://github.com/coreos/etcd/releases/download/v3.0.15/etcd-v3.0.15-linux-amd64.tar.gz -o etcd-v3.0.15-linux-amd64.tar.gz
  - tar xzvf etcd-v3.0.15-linux-amd64.tar.gz
  - ./etcd-v3.0.15-linux-amd64/etcd &
  - go get
  - go get github.com/coreos/go-etcd/etcd

  - go get github.com/rcrowley/go-metrics/stathat
  - go get golang.org/x/net/context
script:
  - go test -tags etcd -bench=. ./...
