sudo: required

language: go

services:
  - docker

go:
  - 1.5
  - 1.6

go_import_path: github.com/skynetservices/skydns

install:
  - go get github.com/coreos/etcd
  - go get github.com/coreos/go-systemd/activation
  - go get github.com/miekg/dns
  - go get github.com/rcrowley/go-metrics
  - go get github.com/prometheus/client_golang/prometheus
  - go get github.com/rcrowley/go-metrics/stathat
  - go get golang.org/x/net/context

before_script:
  - docker run --name etcd quay.io/coreos/etcd:v2.3.6 &
  - sleep 2
